//! Generates enums.sdl.ts and studio's enums.ts from the Prisma enums.
//!
//! Replaces scripts/CodegenPrismaEnums.ts. That built a loosely formatted string and handed it
//! to oxfmt; there is no usable oxc formatter crate (oxc_formatter is a 0.0.0 placeholder) and
//! oxfmt itself ships only as a napi addon, so this emits the final formatted bytes directly.
//! The one formatting rule that matters is the array wrapping in `enums.ts`, below.

use anyhow::Result;
use std::path::Path;

use crate::prisma;

const HEADER: &str = "// This file is auto-generated by 'yarn workspace api script regenerate'";

/// oxfmt's printWidth for enums.ts. A line at exactly this width still fits.
const PRINT_WIDTH: usize = 140;

pub const SDL_OUTPUT: &str = "apps/api.puzzmo.com/src/graphql/enums.sdl.ts";
pub const STUDIO_OUTPUT: &str = "apps/studio/src/lib/enums.ts";
const SCHEMA_DIR: &str = "apps/api.puzzmo.com/prisma/schema";

/// Returns the contents of (enums.sdl.ts, enums.ts) without writing them.
pub fn render(root: &Path) -> Result<(String, String)> {
    let schema = prisma::read_schema_dir(&root.join(SCHEMA_DIR))?;
    let enums = prisma::enums(&schema)?;

    Ok((render_sdl(&enums), render_studio(&enums)))
}

/// The GraphQL SDL, one value per line inside a gql template literal.
fn render_sdl(enums: &[prisma::Enum]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\nimport gql from \"graphql-tag\"\n\nexport const schema = gql`\n");

    for (i, e) in enums.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&format!("  enum {} {{\n", e.name));
        for value in &e.values {
            out.push_str(&format!("    {value}\n"));
        }
        out.push_str("  }\n");
    }

    out.push_str("`\n");
    out
}

/// The studio arrays. Each is one line when it fits in printWidth, otherwise one value per line.
fn render_studio(enums: &[prisma::Enum]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push('\n');

    for e in enums {
        let quoted: Vec<String> = e.values.iter().map(|v| format!("\"{v}\"")).collect();
        let single = format!("export const {}Enum = [{}] as const", e.name, quoted.join(", "));

        out.push('\n');
        if single.len() <= PRINT_WIDTH {
            out.push_str(&single);
            out.push('\n');
        } else {
            out.push_str(&format!("export const {}Enum = [\n", e.name));
            for value in &quoted {
                out.push_str(&format!("  {value},\n"));
            }
            out.push_str("] as const\n");
        }
    }

    out
}
